import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Users from "./components/Users";
import CustomDefineType from "./components/CustomDefineType";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const user1 = {
  name: "Md.Mohiminur Rahman",
  age: 24,
  isRegistered: false,
  lang: ["Bangla", "English"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Users name="Md.Mohiminur Rahman" age={20} isRegistered={true} />
        <CustomDefineType lang={["bangla", "english", "hindi"]} user={user1} />
        <main>{children}</main>
      </body>
    </html>
  );
}
