import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Users from "./components/Users";
import CustomDefineType from "./components/CustomDefineType";
import Card from "./components/Card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const user1 = {
  name: "Md.Mohiminur Rahman",
  age: 24,
  isRegistered: false,
  lang: ["Bangla", "English"],
};

const usersArray = [
  {
    name: "Rahi Rahman",
    age: 24,
    isRegistered: false,
    location: "Mirpur 11",
  },
  {
    name: "Faiaz Hossain",
    age: 24,
    isRegistered: true,
    location: "Mirpur 11",
  },
  {
    name: "Abdul Wasi",
    age: 24,
    isRegistered: false,
    location: "Basundhora R/A",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Users name="Md.Mohiminur Rahman" age={20} isRegistered={true} />
        <CustomDefineType
          lang={["bangla", "english", "hindi"]}
          user={user1}
          usersArr={usersArray}
          status="success"
        />
        <Card>
          <h3>Post Title</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi qui
            vitae dolorem? Vel ullam cum commodi, cupiditate maiores voluptates
            natus sed ex obcaecati vitae iusto animi qui harum asperiores
            voluptatibus!
          </p>
        </Card>
        <main>{children}</main>
      </body>
    </html>
  );
}
